sudo: required
language: java
services:
  - docker
env:
  - CHANGE_MINIKUBE_NONE_USER=true
before_script: # Set up Minishift to deploy an OKD cluster
  - unset _JAVA_OPTIONS # Prevents issues such as formatting the test outputs
  - sudo mount --make-rshared /
  - wget -nv https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - tar -xvf openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz
  - cd openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit
  - export PATH=$PATH:$(pwd)
  - cd ..
  - sudo mv scripts/daemon.json /etc/docker/
  - sudo systemctl restart docker
  - oc cluster up
  - chmod +x scripts/travisTest.sh
  - cd finish/
script: ../scripts/travisTest.sh
branches:
  only: 
  - master
  - qa
  - dev
