language: java
services:
  - docker
before_script:
  - unset _JAVA_OPTIONS # Prevents issues such as formatting the test outputs
  - chmod +x scripts/travisTest.sh
  - cd finish/
script: 
  - ../scripts/travisTest.sh
after_script:
- docker images
- if [[ "$TRAVIS_TEST_RESULT" == "0" ]]; then RESULT="passed"; else RESULT="failed"; fi
- echo -e "\033[1;34m result:\033[0m\033[1;36m $RESULT \033[0m \n"
branches:
  only: 
  - master
  - qa
