apiVersion: v1
kind: Template
metadata:
  name: "build-template"
  annotations:
    description: "Build template for the system and inventory service"
    tags: "build"
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "system-imagestream"
      labels:
        application: "system"
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: "inventory-imagestream"
      labels:
        application: "inventory"
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "system-buildconfig"
      labels:
        build: "system-buildconfig"
    spec:
      source:
        binary: {}
        type: Binary
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "system-imagestream:1.0-SNAPSHOT"
  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: "inventory-buildconfig"
      labels:
        build: "inventory-buildconfig"
    spec:
      source:
        binary: {}
        type: Binary
      strategy:
        type: Docker
      output:
        to:
          kind: ImageStreamTag
          name: "inventory-imagestream:1.0-SNAPSHOT"