# tag::system[]
apiVersion: openliberty.io/v1beta1
# tag::olapp1[]
kind: OpenLibertyApplication
# end::olapp1[]
metadata:
  name: system
  labels:
    name: system
spec:
  # tag::sysImage[]
  applicationImage: guide/system-imagestream:1.0-SNAPSHOT
  # end::sysImage[]
  # tag::replicas[]
  replicas: 3
  # end::replicas[]
  # tag::systemEnv[]
  env:
    - name: KAFKA_SECRET_CA_CRT
      valueFrom:
        secretKeyRef:
          name: kafka-producer-binding
          key: KAFKA_SECRET_CA_CRT
    - name: KAFKAUSER_SECRET_USER_CRT
      valueFrom:
        secretKeyRef:
          name: kafka-producer-binding
          key: KAFKAUSER_SECRET_USER_CRT
    - name: KAFKAUSER_SECRET_USER_KEY
      valueFrom:
        secretKeyRef:
          name: kafka-producer-binding
          key: KAFKAUSER_SECRET_USER_KEY
    - name: BOOTSTRAP_SERVERS
      valueFrom:
        secretKeyRef:
          name: kafka-producer-binding
          key: BOOTSTRAP_SERVERS
    - name: TOPIC
      value: systemloadtopic
    - name: NUMBER_OF_KEYS
      value: "3"
    - name: DELAY_MS
      value: "1000"
    - name: MESSAGE_COUNT
      value: "1000000"
  # end::systemEnv[]
# end::system[]
---
# tag::inventory[]
apiVersion: openliberty.io/v1beta1
# tag::olapp2[]
kind: OpenLibertyApplication
# end::olapp2[]
metadata:
  name: inventory
  labels:
    name: inventory
spec:
  applicationImage: guide/inventory-imagestream:1.0-SNAPSHOT
  # tag::service[]
  service:
    # tag::servicePort[]
    port: 9085
    # end::servicePort[]
  # end::service[]
  # tag::expose[]
  expose: true
  # end::expose[]
  env:
    - name: KAFKA_SECRET_CA_CRT
      valueFrom:
        secretKeyRef:
          name: kafka-consumer-binding
          key: KAFKA_SECRET_CA_CRT
    - name: KAFKAUSER_SECRET_USER_CRT
      valueFrom:
        secretKeyRef:
          name: kafka-consumer-binding
          key: KAFKAUSER_SECRET_USER_CRT
    - name: KAFKAUSER_SECRET_USER_KEY
      valueFrom:
        secretKeyRef:
          name: kafka-consumer-binding
          key: KAFKAUSER_SECRET_USER_KEY
    - name: BOOTSTRAP_SERVERS
      valueFrom:
        secretKeyRef:
          name: kafka-consumer-binding
          key: BOOTSTRAP_SERVERS
    - name: TOPIC
      value: systemloadtopic
    - name: GROUP_ID
      value: system-load-status
    - name: LOG_LEVEL
      value: "INFO"
    - name: MESSAGE_COUNT
      value: "1000000"
# end::inventory[]