apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-consumer
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: systemloadtopic
        operation: Read
      - resource:
          type: topic
          name: systemloadtopic
        operation: Describe
      - resource:
          type: group
          name: my-kafka-consumer
        operation: Read
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-producer
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: systemloadtopic
        operation: Write
      - resource:
          type: topic
          name: systemloadtopic
        operation: Create
      - resource:
          type: topic
          name: systemloadtopic
        operation: Describe